# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dcdkjQ-HiXhzKFk7w6Sgr7y7VPvfgsa9
"""

import os
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# =====================================================================
# STEP 0: EXPANDED DATASET INITIALIZATION (Fixes Naming Discrepancies)
# =====================================================================
csv_filename = "raw_skills.csv"

if not os.path.exists(csv_filename):
    print(f"[{csv_filename} not found. Generating expanded DecodeLabs dataset...]")
    # Expanded with synonyms to bridge the qualitative language barrier (Page 9)
    data = {
        "Job_Role": [
            "Data Scientist",
            "DevOps Engineer",
            "Backend Developer",
            "Cloud Architect",
            "Sys Admin"
        ],
        "Required_Skills": [
            "Python SQL ML Machine Learning Data Analysis Git Artificial Intelligence Statistics",
            "AWS Docker Kubernetes K8s CI/CD Automation Git Python Scripting Jenkins Linux",
            "Java Python SQL APIs Data Structures Backend Git Software Development Django Architecture",
            "AWS Cloud Computing Azure Cloud Security Kubernetes K8s Infrastructure Network DevSecOps",
            "Linux Automation Bash Networking Sys Admin Scripting Systems Administration Security Config"
        ]
    }
    df = pd.DataFrame(data)
    df.to_csv(csv_filename, index=False)
else:
    df = pd.read_csv(csv_filename)

print("✅ Step 0 Complete: Expanded Dataframe 'df' loaded successfully.")


# =====================================================================
# STEP 1: INGESTION (Capturing 3 User Skills to avoid Cold Start)
# =====================================================================
print("\n[STEP 1: INGESTION] Bootstrapping user profile pipeline...")
print("Please enter 3 distinct technical skills:")

user_skills = []
for i in range(1, 4):
    while True:
        skill = input(f" -> Enter skill #{i}: ").strip()
        if len(skill) >= 2:
            user_skills.append(skill)
            break
        print("   ⚠️ Invalid input. Please enter a valid technical skill concept.")

# Combine individual choices into a unified text profile string
user_profile_str = " ".join(user_skills)
print(f"\n✅ User State Captured: '{user_profile_str}'")


# =====================================================================
# STEP 2: SCORING (Vector Mapping, TF-IDF Weighting, & Cosine Similarity)
# =====================================================================
print("\n[STEP 2: SCORING] Translating qualitative text into mathematical vectors...")

job_roles = df["Job_Role"].tolist()
item_contents = df["Required_Skills"].tolist()

# Combine job requirements with user string inside a shared vocabulary space
all_documents = item_contents + [user_profile_str]

# Apply TF-IDF Feature Extraction (Penalizes common words, rewards specific ones)
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(all_documents)

# Separate the document arrays back out
items_vectors = tfidf_matrix[:-1]
user_vector = tfidf_matrix[-1]

# Calculate similarity scores using angle-invariant Cosine Similarity
similarity_scores = cosine_similarity(user_vector, items_vectors).flatten()

# Pair each job role with its newly calculated score
scored_recommendations = list(zip(job_roles, similarity_scores))
print("✅ Scoring math completed successfully.")


# =====================================================================
# STEP 3: SORTING (Ordering Results by Highest Match)
# =====================================================================
print("\n[STEP 3: SORTING] Ordering dataset by descending angular alignment...")
sorted_recommendations = sorted(scored_recommendations, key=lambda x: x[1], reverse=True)


# =====================================================================
# STEP 4: FILTERING (Truncating to Top-3 to Cure Choice Overload)
# =====================================================================
print("[STEP 4: FILTERING] Compiling final Top-N collection...")
print("\n" + "=" * 55)
print("        DECODELABS TECH STACK RECOMMENDATION RESULTS       ")
print("=" * 55)

top_3_results = sorted_recommendations[:3]

# Core Guardrail: Evaluate if the user profile resulted in a 0% match across the board
if top_3_results[0][1] == 0.0:
    print("⚠️ User Cold Start fallback triggered! No matching similarities found.")
    print("💡 Trending Fallbacks Default (Global Popularity):")
    print(" 1. Data Scientist       | Match Score: Baseline Popularity")
    print(" 2. Backend Developer    | Match Score: Baseline Popularity")
    print(" 3. DevOps Engineer      | Match Score: Baseline Popularity")
else:
    for rank, (job, score) in enumerate(top_3_results, 1):
        # Convert the decimal score to an intuitive percentage match
        match_percentage = score * 100
        print(f" Rank {rank}: {job:<22} | Match Score Alignment: {match_percentage:>5.2f}%")

print("=" * 55)